### PR TITLE
fix: cluster list granted to users is incorrect

### LINKED ISSUE #4890: Cluster members cannot access clusters
**Describe the Bug**
Users with only cluster permissions cannot access clusters.

**Versions Used**
KubeSphere: 3.3.0-rc.0

**How To Reproduce**
1. Create a user and assign the `platform-regular` role to the user.
2. Invite the user to a cluster and assign the `cluster-admin` role to the user.
3. Log in as the user. The KS web console provides no interface for the user to access its cluster.

image

image

image

**Expected behavior**
The cluster **Overview** page is displayed after the user logs in.

/assign @zheng1 @wansir @harrisonliu5

### PR DESCRIPTION
**Pull request by wansir**
### What type of PR is this?
/kind bug

### What this PR does / why we need it:

Part of https://github.com/kubesphere/kubesphere/issues/4610, sync granted clusters for users periodically.

### Which issue(s) this PR fixes:

Fixes #4890

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/cluster/cluster_controller.go [hunk 1]
```diff
@@ -25,8 +25,14 @@ import (
 	"fmt"
 	"net/http"
 	"reflect"
+	"strings"
 	"time"
 
+	iamv1alpha2 "kubesphere.io/api/iam/v1alpha2"
+
+	kubesphere "kubesphere.io/kubesphere/pkg/client/clientset/versioned"
+	iamv1alpha2listers "kubesphere.io/kubesphere/pkg/client/listers/iam/v1alpha2"
```
Comment (iawia002) [inline pkg/controller/cluster/cluster_controller.go:34]: Need to be grouped correctly, this is getting more and more chaos

**Review by iawia002 — COMMENTED** [review]
Basically LGTM, just one nit

File: pkg/controller/cluster/cluster_controller.go (hunk 1 above)
Comment (wansir) [reply pkg/controller/cluster/cluster_controller.go:34]: > Need to be grouped correctly, this is getting more and more chaos

It's sorted by `goimports`, using `controller-runtime` instead of the worker queue and informers can keep the code cleanly.

Comment (iawia002) [reply pkg/controller/cluster/cluster_controller.go:34]: > It's sorted by goimports

`goimports` will sort packages within a group, but if they are not originally in a group, `goimports` will do nothing, try this:

```go
import (
	"k8s.io/apimachinery/pkg/api/errors"

	"k8s.io/client-go/discovery"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"k8s.io/client-go/util/retry"

	"github.com/emicklei/go-restful"

	extv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"

	"k8s.io/apimachinery/pkg/runtime/schema"

	urlruntime "k8s.io/apimachinery/pkg/util/runtime"

	"k8s.io/apimachinery/pkg/util/sets"

	"k8s.io/apiserver/pkg/endpoints/handlers/responsewriters"
	unionauth "k8s.io/apiserver/pkg/authentication/request/union"
)
```

> using controller-runtime instead of the worker queue and informers can keep the code cleanly.

You misunderstood, I'm just saying the group is getting more and more.

Comment (wansir) [reply pkg/controller/cluster/cluster_controller.go:34]: got it
