### PR TITLE
Fix: return all items when limit=-1

### LINKED ISSUE #3739: When querying all apps in a project, the interface returns 500
**Describe bug**

when set limit=-1, the interface returns 500

**Environment**
http://139.198.121.240:30881

**How To Reproduce**

kapis/openpitrix.io/v1/workspaces/ws/clusters/host/namespaces/hpro/applications?conditions=status=creating|active|failed|deleting|upgrading|created|upgraded&paging=limit=-1,page=1&orderBy=status_time

**Expected behavior**
The interface returns all apps

**Actual behavior**
image

image

/priority medium
/assign @xyz-li 
/kind bug
/milestone 3.1.0

### PR DESCRIPTION
**Pull request by xyz-li**
Signed-off-by: LiHui <andrewli@yunify.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix: return all items when parameter limit equals 1

**Which issue(s) this PR fixes**:

Fixes #3739

### CODE REVIEW

**Comment by zryfish** [comment]
The whole limit, page idea is to avoid return all of items at one time, we should set default limit instead.

**Comment by xyz-li** [comment]
> The whole limit, page idea is to avoid return all of items at one time, we should set default limit instead.

Resources api are all return all the items when limit equals -1

File: pkg/models/openpitrix/applications.go [hunk 1]
```diff
@@ -308,19 +308,20 @@ func (c *applicationOperator) ListApps(conditions *params.Conditions, orderBy st
 		sort.Sort(HelmApplicationList(apps))
 	}
 
-	items := make([]interface{}, 0, limit)
+	totalCount := len(apps)
```
Comment (zryfish) [inline pkg/models/openpitrix/applications.go:311]: why not using https://github.com/kubesphere/kubesphere/blob/master/pkg/apiserver/query/types.go#L39 to parse request parameters since there are already code to deal with pagination?

Comment (xyz-li) [reply pkg/models/openpitrix/applications.go:312]: The parameter of openpitrix is different from resource api, so I just use the function GetValidPagination.

Comment (zheng1) [reply pkg/models/openpitrix/applications.go:313]: This part of the code will be refactored in the next version. This version is temporarily compatible with the old api
