### PR TITLE
Mix up the pipeline list between ks and Jenkins

### LINKED ISSUE #3081: Inappropriate tips when I open the pipeline list page
As I talked about in the PR title. I got some inappropriate tips that might lead the users to think it's a bug.

The potential reason could be that the Jenkins is not ready. It might occur in a few different phases of Jenkins Pod:

* Init
image

* PodInitializing
image

In order to let you exactly know the meaning of the last screenshot, I already translated it into a human-readable picture.

image

### LINKED ISSUE #3108: Cannot create pipeline due to duplicate name which is invisible
**Describe the Bug**
When I try to create a pipeline, but ks tells me it's a duplicated name. But I cannot see it from the page.

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.0

**Environment**
None.

**How To Reproduce**

**Expected behavior**
No errors happen when someone creates a pipeline.

/kind bug

### PR DESCRIPTION
**Pull request by LinuxSuRen**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Technically we should take the Pipeline list from ks or mixup the instead of only taking it from Jenkins. Because we always manipulate Pipeline from ks.

**Which issue(s) this PR fixes**:
Fixes #3108
Fixes #3081

**Special notes for reviewers**:

**Additional documentation, usage docs, etc.**:

### CODE REVIEW

File: pkg/simple/client/devops/pipeline.go [hunk 1]
```diff
@@ -79,7 +79,7 @@ type Pipeline struct {
 	NumberOfFolders                int           `json:"numberOfFolders,omitempty" description:"number of folders"`
 	NumberOfPipelines              int           `json:"numberOfPipelines,omitempty" description:"number of pipelines"`
 	PipelineFolderNames            []interface{} `json:"pipelineFolderNames,omitempty" description:"pipeline folder names"`
-	WeatherScore                   int           `json:"weatherScore,omitempty" description:"the score to description the result of pipeline activity"`
```
Comment (shaowenchen) [inline pkg/simple/client/devops/pipeline.go:82]: This may result in 500 if the field does not exist. Has it been fully tested?

File: pkg/kapis/devops/v1alpha2/devops.go [hunk 2]
```diff
@@ -41,15 +44,81 @@ func (h *ProjectPipelineHandler) GetPipeline(req *restful.Request, resp *restful
...
+
+	// make sure we have an appropriate value
+	if start, err = strconv.Atoi(req.QueryParameter("start")); err != nil {
+		start = 0
+	}
+	if limit, err = strconv.Atoi(req.QueryParameter("limit")); err != nil {
+		limit = 10
+	}
+
+	defer req.Request.Form.Set("limit", "10000") // assume the pipelines no more than 10k
```
Comment (shaowenchen) [inline pkg/kapis/devops/v1alpha2/devops.go:74]: get the value of the limit from QueryParmeter or set it as 10.  What's the intention here?

File: pkg/kapis/devops/v1alpha2/devops.go [hunk 3]
```diff
@@ -41,15 +44,81 @@ func (h *ProjectPipelineHandler) GetPipeline(req *restful.Request, resp *restful
...
+
+	return h.devopsOperator.ListPipelineObj(namespace, func(list []*v1alpha3.Pipeline, i int, j int) bool {
+		return strings.Compare(list[i].Name, list[j].Name) < 0
```
Comment (shaowenchen) [inline pkg/kapis/devops/v1alpha2/devops.go:77]: Please convert list[i].Name to uppercase and compare it

Comment (LinuxSuRen) [reply pkg/kapis/devops/v1alpha2/devops.go:77]: Are you suggest it should be case insensitive? But according to the naming, the name seems can only be lower-case.

File: pkg/kapis/devops/v1alpha2/devops.go (hunk 2 above)
Comment (LinuxSuRen) [reply pkg/kapis/devops/v1alpha2/devops.go:74]: There are two lists here. And they might have a different order. So this list must be larger than another one. Anyway, the front-end will get the correct data.

File: pkg/simple/client/devops/pipeline.go (hunk 1 above)
Comment (LinuxSuRen) [reply pkg/simple/client/devops/pipeline.go:82]: The front-end cannot see `WeatherScore` if its value is `0`.  Because it is ignored due to `omitempty` field.
An int field always has the default value `0`. So it always has a value. I have no idea which cases might lead to a 500 result.

Comment (shaowenchen) [reply pkg/simple/client/devops/pipeline.go:82]: When it unmarshal JSON data that the field of WeatherScore does not exist, it will result in an error.

File: pkg/kapis/devops/v1alpha2/devops.go (hunk 3 above)
Comment (shaowenchen) [reply pkg/kapis/devops/v1alpha2/devops.go:77]: Before the versions of 3.0, the case was sensitive.

File: pkg/kapis/devops/v1alpha2/devops.go (hunk 2 above)
Comment (shaowenchen) [reply pkg/kapis/devops/v1alpha2/devops.go:74]: It makes me a little confused. Why does it need to set req.Request.Form and req.Request.PostForm at the same time?

File: pkg/kapis/devops/v1alpha2/devops.go (hunk 3 above)
Comment (LinuxSuRen) [reply pkg/kapis/devops/v1alpha2/devops.go:77]: I see.

File: pkg/kapis/devops/v1alpha2/devops.go (hunk 2 above)
Comment (LinuxSuRen) [reply pkg/kapis/devops/v1alpha2/devops.go:74]: [The previous one](https://github.com/kubesphere/kubesphere/pull/3149/files#diff-38024724898ee9b3e4ca7f645d4c19869b100c394ccf587ef1e1ea554f3a7a2aR58) should be moved. It's useless.

File: pkg/simple/client/devops/pipeline.go (hunk 1 above)
Comment (LinuxSuRen) [reply pkg/simple/client/devops/pipeline.go:82]: I cannot produce the error case which you mentioned. But I try to unmarshal a JSON data which does not contain the field WeatherScore, nothing happened. You can run the demo code below:

https://play.golang.org/p/MJFcRRISY4i

File: pkg/kapis/devops/v1alpha2/devops.go (hunk 3 above)
Comment (LinuxSuRen) [reply pkg/kapis/devops/v1alpha2/devops.go]: Fixed it https://github.com/kubesphere/kubesphere/pull/3149/commits/62c297ec53049f2e08e873ea1ee5aa3412b54d5e#diff-38024724898ee9b3e4ca7f645d4c19869b100c394ccf587ef1e1ea554f3a7a2aR76

File: pkg/kapis/devops/v1alpha2/devops.go (hunk 2 above)
Comment (LinuxSuRen) [reply pkg/kapis/devops/v1alpha2/devops.go:73]: fixed it https://github.com/kubesphere/kubesphere/pull/3149/commits/62c297ec53049f2e08e873ea1ee5aa3412b54d5e#diff-38024724898ee9b3e4ca7f645d4c19869b100c394ccf587ef1e1ea554f3a7a2aL58

**Comment by LinuxSuRen** [comment]
Please squash and merge this PR when it's ready. We don't need to keep all the commits, I keep them because force pushing will mash the review process up.
