### PR TITLE
decoupling with Jenkins and LDAP

### LINKED ISSUE #3598: user enters workspace and is prompted to log in again
**Describe the Bug**
**steps:**
1. In a multi-cluster environment, there is a workspace 'ws1' located in the Member cluster
2. User 'ws-manager' with the role of 'ws-manager' log into the platform and enter the workspace 'ws1'

**Expected results:**
can successfully enter into the workspace manage page

**Actual results:**
When enter into the workspace manage page , it is prompted to log in again

image

the host cluster user list:
image

the member cluste user list:
image

the logs of ks-controller-manager:
[ks-controller-manager.log](https://github.com/kubesphere/kubesphere/files/6209924/ks-controller-manager.log)

/kind bug
/assign @wansir 
/priority Medium
/milestone 3.1.0
/area iam

### PR DESCRIPTION
**Pull request by wansir**
Signed-off-by: hongming <talonwan@yunify.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Do not reconcile again if failed syncing data to Jenkins and LDAP. The user status needs to be updated even if LDAP or Jenkins is abnormal. Decoupling with LDAP and Jenkins.

**Which issue(s) this PR fixes**:

Fixes #3598

### CODE REVIEW

**Comment by yuswift** [comment]
@wansir conflicts.

File: pkg/controller/user/user_controller.go [hunk 1]
```diff
@@ -173,36 +177,39 @@ func (c *userController) reconcile(key string) error {
...
+				if err = c.waitForDeleteFromLDAP(key); err != nil {
 					klog.Error(err)
+					c.recorder.Event(user, corev1.EventTypeWarning, controller.FailedSynced, fmt.Sprintf("Failed to sync: %s", err))
 					return err
 				}
 			}
 
 			if err = c.deleteRoleBindings(user); err != nil {
 				klog.Error(err)
+				c.recorder.Event(user, corev1.EventTypeWarning, controller.FailedSynced, fmt.Sprintf("Failed to sync: %s", err))
```
Comment (RolandMa1986) [inline pkg/controller/user/user_controller.go:191]: The message "Failed to sync: %s" is used in many places, consider to define it as constrant.

File: pkg/controller/user/user_controller.go [hunk 2]
```diff
@@ -242,15 +250,17 @@ func (c *userController) reconcile(key string) error {
...
 	}
 
 	if c.devopsClient != nil {
 		// assign jenkins role after user create, assign multiple times is allowed
 		// used as logged-in users can do anything
-		if err = c.assignDevOpsAdminRole(user); err != nil {
+		if err = c.waitForAssignDevOpsAdminRole(user); err != nil {
 			klog.Error(err)
+			c.recorder.Event(user, corev1.EventTypeWarning, controller.FailedSynced, fmt.Sprintf("Failed to sync: %s", err))
 			return err
```
Comment (RolandMa1986) [inline pkg/controller/user/user_controller.go:264]: Should `return err` be removed? Otherwise, reconcile will run again.

File: pkg/controller/user/user_controller.go (hunk 1 above)
Comment (wansir) [reply pkg/controller/user/user_controller.go]: fixed

File: pkg/controller/user/user_controller.go (hunk 2 above)
Comment (wansir) [reply pkg/controller/user/user_controller.go]: fixed

**Comment by RolandMa1986** [comment]
/LGTM
BTW, Ks-controller-mananger won't startup if ldap can't be connected. should this situation be handled too?

**Comment by wansir** [comment]
> /LGTM
> BTW, Ks-controller-mananger won't startup if ldap can't be connected. should this situation be handled too?

Fixed failed unit test. It is currently necessary to create a connection pool and check the connection status after startup.
