### PR TITLE
ignore dryRun k8s request when auditing

### LINKED ISSUE #2422: Duplicate audit logs
**Describe the Bug**
Test to create a stateful service with workloaded created. Check the audit logs and found duplicate logs

Screen Shot 2020-07-14 at 6 43 13 PM

**Versions Used**
KubeSphere: 3.0.0-dev

**Environment**
allinone, logging and audit enabled

**Expected behavior**
The audit logs are not duplicated.

### PR DESCRIPTION
**Pull request by wanjunlei**
Signed-off-by: wanjunlei wanjunlei@yunify.com

**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:

Fixes #2422

### CODE REVIEW

File: pkg/apiserver/auditing/types.go [hunk 1]
```diff
@@ -96,6 +96,17 @@ func (a *auditing) K8sAuditingEnabled() bool {
 //
 func (a *auditing) LogRequestObject(req *http.Request, info *request.RequestInfo) *auditv1alpha1.Event {
 
+	// Ignore the dryRun k8s request.
+	if info.IsKubernetesRequest {
+		values := req.URL.Query()
+		if v, ok := values["dryRun"]; ok {
+			if len(v) > 0 && v[0] == v1.DryRunAll {
```
Comment (zryfish) [inline pkg/apiserver/auditing/types.go:103]: I think we simplify this just check the existence of dryRun, same with k8s https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L421
