### PR TITLE
Fix: filter app by app_id

### LINKED ISSUE #3719: Workspace Column is empty in App Store Reviews page
**Describe the Bug**
Workspace Column is empty in App Store Reviews page

**Versions Used**
KubeSphere: nightly-20210413

**How To Reproduce**
1. Create a new `App Template` under _workspace1_
2. Submit a new `Review` request 
3. Go to the `App Reviews` page and check the list.

There is no **Workspace**  show in the list.

/kind bug
/assign @xyz-li 
/priority medium
/milestone 3.1.0
/area app-management

### PR DESCRIPTION
**Pull request by xyz-li**
Signed-off-by: LiHui <andrewli@yunify.com>

**What type of PR is this?**

/kind bug
/area app-management

**What this PR does / why we need it**:
ks-console need filer app by app_id, ks-apiserver should handle this paramter.
**Which issue(s) this PR fixes**:

Fixes #3719

/assign @zheng1

### CODE REVIEW

File: pkg/models/openpitrix/utils.go [hunk 1]
```diff
@@ -673,6 +673,17 @@ func filterApps(apps []*v1alpha1.HelmApplication, conditions *params.Conditions)
 		return apps
 	}
 
+	// filter app by param app_id
```
Comment (zheng1) [inline pkg/models/openpitrix/utils.go:676]: Should replace with `pkg/models/resources/v1alpha3/interface.go:DefaultList` in next version
