### PR TITLE
Fix: handle invalid semver

### LINKED ISSUE #3552: Applications published via the application template cannot be viewed in the App Store
**Describe the Bug**
**steps:**
1. Publish the app to the App Store in the App Template
2. Goto the App Store, view the published app in step 1

**Expected results:**
can view the published application in the app store

**Actual results:**
Cannot see the published application in the app store

image

/kind bug
/assign @xyz-li 
/priority High
/milestone 3.1.0
/area app-management

### PR DESCRIPTION
**Pull request by xyz-li**
**What type of PR is this?**
/kind bug
/area app-management

**Which issue(s) this PR fixes**:
Handle ks-controller-manager crash when  semantic version is invalid.

Fixes #3552 #3551

### CODE REVIEW

File: pkg/models/openpitrix/utils.go [hunk 1]
```diff
@@ -320,10 +319,16 @@ func convertApp(app *v1alpha1.HelmApplication, versions []*v1alpha1.HelmApplicat
 	} else {
 		out.CategorySet = AppCategorySet{}
 	}
-	if versions != nil && len(versions) > 0 {
-		sort.Sort(AppVersions(versions))
-		out.LatestAppVersion = convertAppVersion(versions[len(versions)-1])
-	} else {
+
+	for ind := range versions {
```
Comment (zheng1) [inline pkg/models/openpitrix/utils.go:323]:
```suggestion
	for _, version := range versions {
```

File: pkg/controller/openpitrix/helmapplication/helm_application_version_controller.go [hunk 2]
```diff
@@ -210,41 +210,42 @@ func (r *ReconcileHelmApplicationVersion) updateStatus(appVersion *v1alpha1.Helm
...
-	}
+	var latestVersionName string
+	var latestSemver *semver.Version
 
-	if verInd == len(l) {
-		return ""
-	}
-
-	latestSemver, _ := semver.NewVersion(l[verInd].GetSemver())
+	for ind := range versions.Items {
```
Comment (zheng1) [inline pkg/controller/openpitrix/helmapplication/helm_application_version_controller.go:224]:
```suggestion
	for _, version := range versions.Items {
```
