### PR TITLE
Use the kube-system UID to identify if the member cluster already exists

### LINKED ISSUE #4625: The host cluster cannot be removed when I add it as a member cluster.
**Describe the Bug**
When I mistakenly managed the host cluster itself as a member cluster, I tried to remove it but could not do so.

**Versions Used**
KubeSphere:v3.2.1
Kubernetes:v1.20

**Environment**
How many nodes and their hardware configuration:
Centos 7/3 master ,4 nodes

**How To Reproduce**
1. In the host cluster, click `Add Cluster`, fill in the related information, and select the `Direct Connection` mode
2. Paste the host cluster's own `Kubeconfig` file into the text box
3. Try to remove the newly managed cluster
image
image
There are no associated action buttons in the red box

**Expected behavior**
I think I cannot add myself as a member cluster,this is unreasonable.

### PR DESCRIPTION
**Pull request by iawia002**
### What type of PR is this?

/kind bug

### What this PR does / why we need it:

See background info and our previous discussion at #4625, We now use the UID of the target cluster's `kube-system` namespace as the unique identifier of the cluster to determine if the cluster already exists.

Screen Shot 2022-01-27 at 11 35 03 AM

### Which issue(s) this PR fixes:

Fixes #4625

### Special notes for reviewers:

This PR also does some code cleanup work, reducing a lot of unnecessary config parsing and client creation.

### Does this PR introduced a user-facing change?

```release-note
NONE
```

### Additional documentation, usage docs, etc.:

```docs

```

/cc @zryfish

### CODE REVIEW

File: pkg/kapis/cluster/v1alpha1/handler.go [hunk 1]
```diff
@@ -372,60 +381,42 @@ func (h *handler) validateKubeConfig(kubeconfig []byte) error {
 		return err
 	}
 
-	// clusters with the exactly same KubernetesAPIEndpoint considered to be one
+	// clusters with the exactly same kube-system namespace UID considered to be one
 	// MUST not import the same cluster twice
-	for _, cluster := range clusters {
-		if len(cluster.Spec.Connection.KubernetesAPIEndpoint) != 0 && cluster.Spec.Connection.KubernetesAPIEndpoint == config.Host {
-			return fmt.Errorf("existing cluster %s with the exacty same server address, MUST not import the same cluster twice", cluster.Name)
+	for _, existedCluster := range clusters {
```
Comment (zryfish) [inline pkg/kapis/cluster/v1alpha1/handler.go:386]: Could we add the clusterid to the status of Cluster object? I think we can use it in other scenarios too, it would also be easier to check clusterid here.

Comment (iawia002) [reply pkg/kapis/cluster/v1alpha1/handler.go:386]: I'm cool with this idea, but I think we should add it into an annotation, it's not a status message.

Comment (zryfish) [reply pkg/kapis/cluster/v1alpha1/handler.go:386]: Status usually set by controller, means watched state, which is exactly our case, I think it's fine to set it into status.

Comment (iawia002) [reply pkg/kapis/cluster/v1alpha1/handler.go:386]: I added a new `UID` field to status, PTAL

Comment (zryfish) [reply pkg/kapis/cluster/v1alpha1/handler.go:386]: Seen it, but there are too many changes on CRD yamls which shouldn't be. It's better to make changes only related to this RP.

Comment (iawia002) [reply pkg/kapis/cluster/v1alpha1/handler.go:386]: I have submitted a PR to update the automatically generated files separately, we need to merge that first: #4669

Comment (iawia002) [reply pkg/kapis/cluster/v1alpha1/handler.go:386]: Updated, PATL
