### PR TITLE
fix: synchronize users to LDAP

### LINKED ISSUE #2198: Add  user to ldap
```bash
org.acegisecurity.userdetails.UsernameNotFoundException: User admin not found in directory.
	at org.acegisecurity.ldap.search.FilterBasedLdapUserSearch.searchForUser(FilterBasedLdapUserSearch.java:126)
	at hudson.security.LDAPSecurityRealm$LDAPUserDetailsService.loadUserByUsername(LDAPSecurityRealm.java:1314)
	at hudson.security.LDAPSecurityRealm$LDAPUserDetailsService.loadUserByUsername(LDAPSecurityRealm.java:1251)
	at jenkins.security.ImpersonatingUserDetailsService.loadUserByUsername(ImpersonatingUserDetailsService.java:30)
	at hudson.model.User.getUserDetailsForImpersonation(User.java:394)
```

DevOps use LDAP to manager users. It is necessary to sync users from Auth to OpenLDAP

version: 20200613 installer 
/area  iam
/assign @wansir

### PR DESCRIPTION
**Pull request by wansir**
Signed-off-by: hongming <talonwan@yunify.com>

**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:

Synchronize users to LDAP.

**Which issue(s) this PR fixes**:

Fixes #2198

### CODE REVIEW

File: pkg/controller/user/user_controller.go [hunk 1]
```diff
@@ -239,6 +243,48 @@ func (c *Controller) reconcile(key string) error {
...
+			if _, err := c.ksClient.IamV1alpha2().Users().Update(user); err != nil {
+				return err
+			}
+		}
+
+		// Our finalizer has finished, so the reconciler can do nothing.
+		return nil
+	}
+
+	if err = c.ldapSync(user); err != nil {
```
Comment (zryfish) [inline pkg/controller/user/user_controller.go:283]: What if ldapClient is nil ?

File: pkg/controller/user/user_controller.go [hunk 2]
```diff
@@ -419,6 +464,25 @@ func (c *Controller) updateFederatedUser(fedUser *iamv1alpha2.FederatedUser) err
 	return nil
 }
 
+func (c *Controller) ldapSync(user *iamv1alpha2.User) error {
+	encrypted, _ := strconv.ParseBool(user.Annotations[iamv1alpha2.PasswordEncryptedAnnotation])
+	if encrypted {
```
Comment (zryfish) [inline pkg/controller/user/user_controller.go:469]: Don't sync user if the password is encrypted, why ?

Comment (wansir) [reply pkg/controller/user/user_controller.go:469]: Use encrypted password cannot logged in through LDAP. Jenkins authorization mode `Logged in users can do anything` just lookup authenticated user in LDAP, user password  is not important, because regular users are not allowed to log in to Jenkins directly.

File: pkg/controller/user/user_controller.go (hunk 1 above)
Comment (zryfish) [reply pkg/controller/user/user_controller.go:283]: Is any comments on this?

Comment (wansir) [reply pkg/controller/user/user_controller.go:283]: LDAP needs to be enabled during installation, must not be nil. Use simple ldap client in debug mode.

Comment (zryfish) [reply pkg/controller/user/user_controller.go:283]: Then we'd better check client during controller initialization, make sure we don't get a nil ldap client

Comment (wansir) [reply pkg/controller/user/user_controller.go:283]: Is it necessary to use simple LDAP client if LDAP options not provide?

Comment (zryfish) [reply pkg/controller/user/user_controller.go:283]: No, if ldap not provided, just return error. Simple Ldap is only used for testing

Comment (wansir) [reply pkg/controller/user/user_controller.go:283]: done
