### PR TITLE
Fix crash caused by resouce discovery failed

### LINKED ISSUE #4039: ks-apiserver crash due to resources discovery failed
**Describe the Bug**

`ks-apiserver` to fail to start, resources discovery reported some error. Similar with #1962.

```
Error: unable to retrieve the complete list of server APIs: actions.kio.kasten.io/v1alpha1: the server is currently unable to handle the request, apps.kio.kasten.io/v1alpha1: the server is currently unable to handle the request, vault.kio.kasten.io/v1alpha1: the server is currently unable to handle the request
2021/07/02 14:07:13 unable to retrieve the complete list of server APIs: actions.kio.kasten.io/v1alpha1: the server is currently unable to handle the request, apps.kio.kasten.io/v1alpha1: the server is currently unable to handle the request, vault.kio.kasten.io/v1alpha1: the server is currently unable to handle the request
```

/kind bug
/milestone BackLog

### PR DESCRIPTION
**Pull request by wansir**
### What type of PR is this?
/kind bug

### What this PR does / why we need it:

Currently, the discovery client will list all group version resources, if the aggregated API server occurs some exceptions, the discovery client could not work well with `discoveryclient.ServerGroupsAndResources()`.  It's unexpected that unhealthy APIService caused the ks-apiserver crash. I modified the waitForResourceSync method, the discovery client only focuses on the resources on which we depend.

### Which issue(s) this PR fixes:

Fixes #4039

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/apiserver/apiserver.go [hunk 1]
```diff
@@ -26,6 +26,9 @@ import (
 	"sync"
 	"time"
 
+	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/client-go/util/retry"
+
```
Comment (iawia002) [inline pkg/apiserver/apiserver.go:31]: Need to be put together with the following group

File: pkg/apiserver/apiserver.go [hunk 2]
```diff
@@ -367,211 +370,215 @@ func (s *APIServer) waitForResourceSync(ctx context.Context) error {
...
-
-	for _, gvr := range k8sGVRs {
-		if !isResourceExists(gvr) {
-			klog.Warningf("resource %s not exists in the cluster", gvr)
-		} else {
-			_, err := s.InformerFactory.KubernetesSharedInformerFactory().ForResource(gvr)
-			if err != nil {
-				klog.Errorf("cannot create informer for %s", gvr)
+	type informerForResourceFunc func(resource schema.GroupVersionResource) (interface{}, error)
+	waitForResourceSync := func(sharedInformerFactory informers.GenericInformerFactory, informerForResourceFunc informerForResourceFunc, GVRs map[schema.GroupVersion][]string) error {
```
Comment (iawia002) [inline pkg/apiserver/apiserver.go:383]: Can we move these two function definitions out of the function body? This makes the `APIServer`'s `waitForResourceSync` function too long

File: pkg/apiserver/apiserver.go (hunk 1 above)
Comment (wansir) [reply pkg/apiserver/apiserver.go:31]: Code formatted  by `hack/update-gofmt.sh` and `update-goimports.sh`.

File: pkg/apiserver/apiserver.go (hunk 2 above)
Comment (wansir) [reply pkg/apiserver/apiserver.go:383]: Forgot to hold this PR. I agree with you, the code smells bad.
