### PR TITLE
Fix: fix app repo and helm app bugs

### LINKED ISSUE #3556: The name of the application template is incorrect on the application review page
**Describe the Bug**

**steps:**
1. In the application template detail page, change the name of the application template
2. Select the version of the application under the application template and submit it for review
3. Enter the App Store -- >the Application Review page, view the name of the application template in the Application Review list

**Expected results:**
In the Application Review list, the name of the application template is the modified name

**Actual results:**
In the Application Review list, the name of the application template is the same as before the change

image

/kind bug
/assign @xyz-li
/priority Medium
/milestone 3.1.0
/area app-management

### LINKED ISSUE #3633: In the edit template repository page, the value of access info is not displayed
**Describe the Bug**
In the edit template repository page, the value of access info is not displayed
image

/kind bug
/assign @xyz-li 
/priority Medium
/milestone 3.1.0
/area app-management

### LINKED ISSUE #3634: The application repository could not be successfully edited
**Describe the Bug**
The application repository could not be successfully edited
image

/kind bug
/assign @xyz-li 
/priority High
/milestone 3.1.0
/area app-management

### LINKED ISSUE #3636: Message information is not displayed in the application repository event page
**Describe the Bug**

Message information is not displayed in the application repository event page
image

and the creator is not displayed:
image

/kind bug
/assign @xyz-li 
/priority Medium
/milestone 3.1.0
/area app-management

### PR DESCRIPTION
**Pull request by xyz-li**
**What type of PR is this?**
/kind bug
/kind flake

**Which issue(s) this PR fixes**:
Fixes #3636
Fixes #3634
Fixes #3633
Fixes #3556

### CODE REVIEW

File: pkg/models/openpitrix/applicationversions.go [hunk 1]
```diff
@@ -230,8 +230,11 @@ func (c *applicationOperator) ListAppVersionReviews(conditions *params.Condition
 	items := make([]interface{}, 0, len(filtered))
 
 	for i, j := offset, 0; i < len(filtered) && j < limit; i, j = i+1, j+1 {
-		review := convertAppVersionReview(filtered[i])
-		items = append(items, review)
+		app, err := c.appLister.Get(filtered[i].GetHelmApplicationId())
+		if err == nil {
+			review := convertAppVersionReview(app, filtered[i])
+			items = append(items, review)
+		}
```
Comment (zheng1) [inline pkg/models/openpitrix/applicationversions.go:237]: Should log the error or return it
