### PR TITLE
use CSR to generate user client certificate

### LINKED ISSUE #1752: devops kubeconfig认证失败
> 异常信息

```
Starting Kubernetes deployment
ERROR: ERROR: java.lang.RuntimeException: java.io.IOException: PEM is invalid: no begin marker
hudson.remoting.ProxyException: java.lang.RuntimeException: java.io.IOException: PEM is invalid: no begin marker
```

_用户：admin_
_kubeconfig生成方式：自动生成_

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01ERXdNVEE0TWpVMU1sb1hEVEk1TVRJeU9UQTRNalUxTWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTm9sCmh2dEkvMEZJMUd1R0tiRHFYSWFHdWxPMzVaMFVMNTFiRFdXQXE4ekI1Sng1YlVWaG9CaUg3ZFZ2UnB1eGpGL2YKVElPaFpDdCsvYmFCK2NFZjcrMklSZjRrVkJhZzFjbXQ5SFBaRlRvYnRJbUFvNnd4RHRPQmM2VFFFODZ5VTU3YQp4ekVIKy90ODNScHhOc0FaWmVncndzd0pjUUpLK0p6aGw0NExrQVNsaWxpVENuYWI4UXdTb203cVJUSmZ4Y2RRCk9Nb2Zwc0lJcXlTNVhGNldOdUVaN0MwcGFudk9nMWIvcWVFSFVLVG9yU0dxejFMUTEzK0txRXUrajU2RjM1MkUKNmVlR2F6UklraGszZEZCNzdGUFdBK3psNURDeW40MitWYXpFbnVnb0RjUlVQeXRrMHluQ05DeUlqUEgybVBNRQpVUnN0OUpJUWw3c3VqOXU1SXRzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDWFd5NkdjOHRUZjBPU2pCR2ZhbWNzaUpzQ3EKazVHeXNkYyt6eEtzNUJNL3g5N3oyUndUV2FuczVJMjAxbkpzOTBFTzRvaGxHQjRzNHRHZmQzOFVNQnl0TlNjcQo2RWxXclRVS2VTYkhocTltUERKczA3UGpoWHZIRFBYM2RFZTVTN09IQVJDam1NTittd2U0WXBqTWVHSUdwRm5LCnNOVHFiTkFkaTd5MjZXQVdsRk5XampNS0hidjd3WStYeGlmQm1xOTFSdnBORGhOb0Vma2NGWFRPSnYxdEtQY3EKZ0JKQmpZU01hTHJMbmNQekZSVzIyZWMrQ0MwSDQ4QkRGa0k1R1JaSEQydVNtL0VQUTR6dXQrK0oycUhVQjhRRAphTThzMFVSOHh1dVAyekh0T2RMNXA3QkFqWXU4b0RKc0lWcjREL2I2b0VvRjhSWStkdU9iZFhHWHJoUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://10.96.0.1:443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
    namespace: default
  name: admin@kubernetes
current-context: admin@kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: ""
    client-key-data: ""
```

content换成/projects/kubesphere-controls-system/configmaps/kubeconfig-admin/detail值，
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01ERXdNVEE0TWpVMU1sb1hEVEk1TVRJeU9UQTRNalUxTWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTm9sCmh2dEkvMEZJMUd1R0tiRHFYSWFHdWxPMzVaMFVMNTFiRFdXQXE4ekI1Sng1YlVWaG9CaUg3ZFZ2UnB1eGpGL2YKVElPaFpDdCsvYmFCK2NFZjcrMklSZjRrVkJhZzFjbXQ5SFBaRlRvYnRJbUFvNnd4RHRPQmM2VFFFODZ5VTU3YQp4ekVIKy90ODNScHhOc0FaWmVncndzd0pjUUpLK0p6aGw0NExrQVNsaWxpVENuYWI4UXdTb203cVJUSmZ4Y2RRCk9Nb2Zwc0lJcXlTNVhGNldOdUVaN0MwcGFudk9nMWIvcWVFSFVLVG9yU0dxejFMUTEzK0txRXUrajU2RjM1MkUKNmVlR2F6UklraGszZEZCNzdGUFdBK3psNURDeW40MitWYXpFbnVnb0RjUlVQeXRrMHluQ05DeUlqUEgybVBNRQpVUnN0OUpJUWw3c3VqOXU1SXRzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDWFd5NkdjOHRUZjBPU2pCR2ZhbWNzaUpzQ3EKazVHeXNkYyt6eEtzNUJNL3g5N3oyUndUV2FuczVJMjAxbkpzOTBFTzRvaGxHQjRzNHRHZmQzOFVNQnl0TlNjcQo2RWxXclRVS2VTYkhocTltUERKczA3UGpoWHZIRFBYM2RFZTVTN09IQVJDam1NTittd2U0WXBqTWVHSUdwRm5LCnNOVHFiTkFkaTd5MjZXQVdsRk5XampNS0hidjd3WStYeGlmQm1xOTFSdnBORGhOb0Vma2NGWFRPSnYxdEtQY3EKZ0JKQmpZU01hTHJMbmNQekZSVzIyZWMrQ0MwSDQ4QkRGa0k1R1JaSEQydVNtL0VQUTR6dXQrK0oycUhVQjhRRAphTThzMFVSOHh1dVAyekh0T2RMNXA3QkFqWXU4b0RKc0lWcjREL2I2b0VvRjhSWStkdU9iZFhHWHJoUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://kubernetes.default.svc
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
    namespace: default
  name: admin@kubernetes
current-context: admin@kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlc3BoZXJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlc3BoZXJlLXRva2VuLXdrNmpxIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Imt1YmVzcGhlcmUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIzOTQyNWEzNS0yODk4LTQwMDYtYjRhZS05NmM2N2YzNzFhYzgiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXNwaGVyZS1zeXN0ZW06a3ViZXNwaGVyZSJ9.ksNI0T2lkWW0U_L2KAsP1tDA_2Chkb0bfMzHnJ1-uTaeK924kgvKAzR2PGUkHtpkTCsrV7oxLFDCNsCtc29OEufh0ARBraGNtV1ubZtdfWbCF6FVmr8SEyqmJ979LXIzY_k9FoN-Nk2IQaT2ck7vSgfiWzet3zS4IN4zYLnkw-NN8R1Yq2UpHkGOaiVUJeVWoO4spEVof8v3dDFbPyQuKsIiYnT4jfa9jcZjpTfwKcyJtv2oynLtM99vb7_vxD5TdMqURjTNF-_yk31bUj8EBkqishzEvySugdJs9VWwk5JmEAC4tG0qI8hFn3LaTpWcWQ0K6ZeVB5t9_Qv78g85Pg

```

>  异常变为

```
Starting Kubernetes deployment
Loading configuration: /home/jenkins/agent/workspace/project-ZV3QYD0PAAqz/zuul-pipline/deploy/dev/devops-sample-svc.yaml
ERROR: ERROR: java.lang.RuntimeException: io.kubernetes.client.ApiException: Unauthorized
hudson.remoting.ProxyException: java.lang.RuntimeException: io.kubernetes.client.ApiException: Unauthorized
```

请问有处理的方向吗？

除了系统admin用户，其他用户都是ldap接入进来的

### PR DESCRIPTION
**Pull request by wansir**
Signed-off-by: hongming <talonwan@yunify.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Use CSR to generate user client certificate.

**Which issue(s) this PR fixes**:

Fixes #1752 #1695 #1449

### CODE REVIEW

File: pkg/models/kubeconfig/kubeconfig.go [hunk 1]
```diff
@@ -21,295 +21,210 @@ package kubeconfig
...
-	tmpUser := user{User: userInfo{CaData: cert, KeyData: key}, Name: username}
-	tmpKubeConfig.Users = append(tmpKubeConfig.Users, tmpUser)
-	tmpKubeConfig.CurrentContext = contextName
+	cert := k8sCSR.Status.Certificate
+
+	config := clientcmdapi.Config{
+		Kind:        "Config",
+		APIVersion:  "v1",
+		Preferences: clientcmdapi.Preferences{},
+		Clusters: map[string]*clientcmdapi.Cluster{"cluster.local": {
```
Comment (zryfish) [inline pkg/models/kubeconfig/kubeconfig.go]: do not hard code `cluster.local`, users may use a different domain

File: pkg/models/kubeconfig/kubeconfig.go [hunk 2]
```diff
@@ -21,295 +21,210 @@ package kubeconfig
...
+	// create csr
+	k8sCSR, err = k8sClient.CertificatesV1beta1().CertificateSigningRequests().Create(k8sCSR)
 
-	crt, pri, err := Parse(caPath, keyPath)
 	if err != nil {
-		klog.Error(err)
-		return "", "", err
+		klog.Errorln(err)
+		return nil, err
 	}
```
Comment (zryfish) [inline pkg/models/kubeconfig/kubeconfig.go]: I think we can use a defer deleting here in case of `creating/updating/approving` failed. Otherwise, if users tried to create a kubeconfig if there is an error, definitely will fail again.

File: pkg/models/kubeconfig/kubeconfig.go [hunk 3]
```diff
@@ -21,295 +21,210 @@ package kubeconfig
...
 	if err != nil {
-		return "", err
+		klog.Errorln(err)
+		return nil, err
 	}
 
-	tmpUser := user{User: userInfo{CaData: cert, KeyData: key}, Name: username}
-	tmpKubeConfig.Users = append(tmpKubeConfig.Users, tmpUser)
-	tmpKubeConfig.CurrentContext = contextName
+	cert := k8sCSR.Status.Certificate
```
Comment (zryfish) [inline pkg/models/kubeconfig/kubeconfig.go]: need to check cert before using it, what if `Certificate` is empty

File: pkg/models/kubeconfig/kubeconfig.go [hunk 4]
```diff
@@ -21,295 +21,210 @@ package kubeconfig
...
+		klog.Errorln(err)
 		return "", err
 	}
+
 	return string(data), nil
 }
 
 func DelKubeConfig(username string) error {
 	k8sClient := client.ClientSets().K8s().Kubernetes()
 	configName := fmt.Sprintf("kubeconfig-%s", username)
```
Comment (zryfish) [inline pkg/models/kubeconfig/kubeconfig.go]: should use string template variable instead of hardcoding

File: pkg/models/kubeconfig/kubeconfig.go (hunk 1 above)
Comment (wansir) [reply pkg/models/kubeconfig/kubeconfig.go]: `cluster.local` is default cluster name, not domain.

File: pkg/models/kubeconfig/kubeconfig.go [hunk 5]
```diff
@@ -21,295 +21,228 @@ package kubeconfig
...
+		if k8sCSR != nil && k8sCSR.Status.Certificate != nil {
+			cert = k8sCSR.Status.Certificate
+			break
+		}
 
-	config, err := yaml.Marshal(tmpKubeConfig)
-	if err != nil {
-		return "", err
+		// sleep 0/1/2 second
+		time.Sleep(time.Second * time.Duration(i))
```
Comment (zryfish) [inline pkg/models/kubeconfig/kubeconfig.go]: this is not a good practice, the api here is synchronous, it means it will take at most 3 seconds for this api to be completed and it may still failed.  I think either 1) build this logic into a controller 2) lower the sleep duration. I prefer the first solution, the second is temporary .

File: pkg/models/kubeconfig/kubeconfig.go [hunk 6]
```diff
@@ -21,295 +21,228 @@ package kubeconfig
...
 )
 
 const (
-	caPath           = "/etc/kubernetes/pki/ca.crt"
-	keyPath          = "/etc/kubernetes/pki/ca.key"
-	clusterName      = "kubernetes"
-	kubectlConfigKey = "config"
-	defaultNamespace = "default"
+	kubeconfigNameFormat = "kubeconfig-%s"
+	defaultClusterName   = "cluster.local"
```
Comment (zryfish) [inline pkg/models/kubeconfig/kubeconfig.go]: does this cluster name mean something? why it have to be `cluster.local`, same with the default domain name, it's misleading

File: pkg/models/kubeconfig/kubeconfig.go (hunk 5 above)
Comment (wansir) [reply pkg/models/kubeconfig/kubeconfig.go]: This part of the code will be moved to the controller in 3.0. It's just a workaround for 2.1.1, kubeconfig can be recreate even if it fails.

File: pkg/models/kubeconfig/kubeconfig.go [hunk 7]
```diff
@@ -21,294 +21,225 @@ package kubeconfig
...
-
-	contextName := username + "@" + clusterName
-	tmpContext := contextObject{Context: contextInfo{User: username, Cluster: clusterName, NameSpace: defaultNamespace}, Name: contextName}
-	tmpKubeConfig.Contexts = append(tmpKubeConfig.Contexts, tmpContext)
 
-	cert, key, err := generateCaAndKey(username, caPath, keyPath)
+	// get client cert
+	var cert []byte
+	maxRetries := 3
+	for i := 0; i < maxRetries; i++ {
```
Comment (zryfish) [inline pkg/models/kubeconfig/kubeconfig.go]: I think we need to refactor this in next release.

Comment (wansir) [reply pkg/models/kubeconfig/kubeconfig.go]: This part of the code will be moved to the controller in 3.0. It's just a workaround for 2.1.1, kubeconfig can be recreate even if it fails.

Comment (zryfish) [reply pkg/models/kubeconfig/kubeconfig.go]: ok
