### PR TITLE
legacy API compatibility

### LINKED ISSUE #2612: user could not see devops project after he was invited as operator
**Describe the Bug**

The user is a `ws-self-provisioner`. He was invited as operator of a devops project by the project admin, but he could not see the project

**Versions Used**
KubeSphere(2020-07-25)

/kind bug
/milestone 3.0.0
/area devops
/assign @shaowenchen

### PR DESCRIPTION
**Pull request by wansir**
Signed-off-by: hongming <talonwan@yunify.com>

**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:

legacy devps API compatibility.

**Which issue(s) this PR fixes**:

Fixes #2612

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by zryfish** [comment]
unit test fail, please do unit testing locally before submitting your PR

File: pkg/controller/devopsproject/devopsproject_controller.go [hunk 1]
```diff
@@ -254,6 +254,10 @@ func (c *Controller) syncHandler(key string) error {
 				ns := c.generateNewNamespace(project)
 				ns, err := c.client.CoreV1().Namespaces().Create(ns)
 				if err != nil {
+					// recreate devops with generateName if admin namespace is conflict
+					if errors.IsAlreadyExists(err) && project.GenerateName != "" {
+						return c.recreateDevOpsProject(project)
```
Comment (shaowenchen) [inline pkg/controller/devopsproject/devopsproject_controller.go:259]: It will cause the data of users to lose if there is the same name of DevOps.

Comment (wansir) [reply pkg/controller/devopsproject/devopsproject_controller.go:259]: This is the logic of DevOps project creation, regenerate DevOps project ID if admin namespace is conflicted. DevOps project associated with the Jenkins project(admin namespace) will not be recreated.

Comment (shaowenchen) [reply pkg/controller/devopsproject/devopsproject_controller.go:258]: If you delete devopproject  obj，the project in jenkins will be deleted

https://github.com/kubesphere/kubesphere/blob/3c8fbe39b971108c81d41b683caf8c9b45437963/pkg/controller/devopsproject/devopsproject_controller.go#L310

Comment (wansir) [reply pkg/controller/devopsproject/devopsproject_controller.go:258]: https://github.com/kubesphere/kubesphere/blob/3c8fbe39b971108c81d41b683caf8c9b45437963/pkg/controller/devopsproject/devopsproject_controller.go#L208-L253

Admin namespace is empty, there is no namespace association,  because the admin namespace creation conflict.

Comment (wansir) [reply pkg/controller/devopsproject/devopsproject_controller.go:258]: We need to make sure that the admin namespace is created properly, regenerate project ID is needed.

File: pkg/models/devops/devops.go [hunk 2]
```diff
@@ -866,6 +895,21 @@ func (d devopsOperator) ToJson(req *http.Request) (*devops.ResJson, error) {
 	return res, err
 }
 
+func (d devopsOperator) generateNameIsUnique(workspace, generateName string) (bool, error) {
```
Comment (zryfish) [inline pkg/models/devops/devops.go:898]: I prefer `isGenerateNameUnique`

File: pkg/models/devops/devops.go [hunk 3]
```diff
@@ -143,7 +146,30 @@ func convertToHttpParameters(req *http.Request) *devops.HttpParameters {
...
+		klog.Error(err)
+		return nil, err
+	}
+
+	// ensure generateName is unique in workspace scope
+	if unique, err := d.generateNameIsUnique(workspace, project.GenerateName); err != nil {
+		return nil, err
+	} else if !unique {
+		err = errors.NewConflict(devopsv1alpha3.Resource(devopsv1alpha3.ResourceSingularDevOpsProject),
+			project.GenerateName, fmt.Errorf("already exist in workspace scope"))
```
Comment (zryfish) [inline pkg/models/devops/devops.go:162]: The error message should be more informative. 
```suggestion
			project.GenerateName, fmt.Errorf("a devops project named %s already exists in the workspace", project.GenerateName))
```
